### ISSUE TITLE
View and Create Deployments

### ISSUE THREAD

**Issue by saidghamra** [AgoraCloud/ui#13]
When creating a deployment, the user should be prompted to enter the following information:
- [x] Step 1: Name the deployment
- [x] Step 2: Choose the code-server image name and tag
- [x] Step 3: Enter the sudo password for the container
- [x] Step 4: Specify the resources (cpu, memory and storage)
- [x] Step 5: Create the deployment

**Comment by MarcDAFrame** [comment]
https://material-ui.com/components/floating-action-button/

![image](https://user-images.githubusercontent.com/12240832/107818647-ef4e7700-6d45-11eb-9e6d-f0615a460856.png)
* floating action button in the bottom right

**Comment by MarcDAFrame** [comment]
# TODO
- [ ] design create deployment page
- [ ] style the `deployment cards`
  - add launch button
  - deployment status
  - display deployment resources

**Comment by saidghamra** [comment]
**Quick Fixes:**

- [ ] CPU and RAM input fields should be mandatory
- [ ] Add a switch `Persist`, if enabled show the mandatory storage input field
- [ ] Load all available deployment images via the `api/workspaces/:workspaceId/images` endpoint
- [ ] Rename Sudo Password field to Sudo Password
- [ ] Reset create deployments form on creation or navigation away from the page

**Comment by saidghamra** [comment]
In `develop`
